homeassistant:

zone:

  - name: home
    latitude: !secret latitude_home
    longitude: !secret longitude_home
    radius: 50
    icon: mdi:home

  - name: notrabalho
    latitude: !secret latitude_tiago_work
    longitude: !secret longitude_tiago_work
    radius: 700
    icon: mdi:airplane

device_tracker:
  
  - platform: mqtt_json
    devices:
     tiago: zanzito/tiago/location
    track_new_devices: True
    interval_seconds: 10
    consider_home: 20
    
sensor:
  
  - platform: mqtt
    state_topic: "zanzito/tiago/battery_level"
    name: "Tiago Bateria Telemovel"
    unit_of_measurement: '%'
    retain: true
  
  - platform: template
    sensors:
      tiago:
        friendly_name: 'Estado Tiago'
        value_template: > 
            {%- if is_state('device_tracker.tiago', 'not_home') -%}
               Ausente
            {%- endif -%}
            {%- if is_state('device_tracker.tiago', 'home') -%}
               Em Casa
            {%- endif -%}      
            {%- if is_state('device_tracker.tiago', 'notrabalho') -%} 
               No Trabalho
            {%- endif -%}

camera:
  
  - name: tiago_cam
    platform: generic
    still_image_url: https://maps.googleapis.com/maps/api/staticmap?center={{ states.device_tracker.tiago.attributes.latitude }},{{ states.device_tracker.tiago.attributes.longitude }}&zoom=16&size=500x500&maptype=roadmap&markers=color:green%7Clabel:JA%7C{{ states.device_tracker.tiago.attributes.latitude }},{{ states.device_tracker.tiago.attributes.longitude }}
    limit_refetch_to_url_change: true  




